ttl_min = 23
ttl_max = 60

MAX_TTL = 255

MIN_SRC_PORT = 1024
MAX_SRC_PORT = 49151

PROBE_TIMEOUT = 6
IP_DF_FLAG = 0x02

TCP_FIN_FLAG = 0x01
TCP_SYN_FLAG = 0x02
TCP_RST_FLAG = 0x04
TCP_PSH_FLAG = 0x08
TCP_ACK_FLAG = 0x10
TCP_URG_FLAG = 0x20
TCP_ECE_FLAG = 0x40
TCP_CWR_FLAG = 0x80

SG_PROBE_SLEEP_TIME = 0.1

TCP_ECE_FLAG_CHAR = "E"
TCP_URG_FLAG_CHAR = "U"
TCP_ACK_FLAG_CHAR = "A"
TCP_PSH_FLAG_CHAR = "P"
TCP_RST_FLAG_CHAR = "R"
TCP_SYN_FLAG_CHAR = "S"
TCP_FIN_FLAG_CHAR = "F"

BASIC_UDP_HEADER_LENGTH = 328

NUMBER_OF_TESTS = 13

TOP_MATCHING_OS = 3

PORT_LIST_FILE = "ports.pkl"
NMAP_DB_FILE = "nmap-os-db.txt"

DB_COMMENT_CHAR = "#"
DB_SPLIT_OPTIONS = "|"
DB_GREATER_THAN = ">"
DB_LOWER_THAN = "<"
DB_RANGE = "-"